### ISSUE TITLE
Update color if changed

### ISSUE THREAD

**Issue by jfexyz** [codenameyau/github-label#31]
If the label already exists, but the color specified in the preset has changed, the label should be updated and not skipped.

**Comment by codenameyau** [comment]
`v1.2.1` contains the update.

Here's a usage example and output after changing the color of the "priority 1: urgent" label.

``` bash
$ node github-label.js 'codenameyau/github-label' -p priority 
[-] Skipped label: "priority 3: medium"
[-] Skipped label: "priority 2: high"
[+] Updated label: "priority 1: urgent"
[-] Skipped label: "priority 4: low"
```
